export { Page1 as One } from "./Page1";
export { Page2 as Two } from "./Page2";
export { Page3 as Three } from "./Page3";
export { Page4 as Four } from "./Page4";
export { PageRegister as Registrar } from "./PageRegister";
export { PageLogin as Entrar } from "./PageLogin";
export { PageInicio as Inicio } from "./PageInicio";
export { PageList as List } from "./PageList";
export { CadList as Cad } from './CadList'